accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
  url(r'^signup/$', views.signup_view, name="signup"),
  url(r'^login/$', views.login_view, name="login"),
  url(r'^logout/$', views.logout_view, name="logout"),

]

articles/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

portfolio/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    url(r'^$', views.project_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$', views.project_detail, name="details"),
]

wannabeblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from portfolio import views as project_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^portfolio/', include('portfolio.urls', namespace="project")),
    url(r'^about/$', views.about, name="about"),
    url(r'^$', views.homepage, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default='default.png', blank=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
  


def __str__(self):
	return self.title

def snippet(self):
	return self.body[:100] + '...'

portfolio/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Project(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(default=datetime.now, blank=True)
	thumb = models.ImageField(default='default.png', blank=True)
	urlDemo = models.URLField(null=True, blank=True)
	urlGit = models.URLField(null=True, blank=True)



	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:300] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('article:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('article:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('article:list')

articles/views.py
from django.shortcuts import render, redirect
from . models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def article_list(request):
	articles = Article.objects.all().order_by('date')
	return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
	# return HttpResponse(slug)

	article = Article.objects.get(slug=slug)
	return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('article:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

portfolio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import Project


# Create your views here.



def project_list(request):
    
    project = Project.objects.all()
    context = {
    'project': project
  }
    return render(request, 'portfolio/project_list.html', context)

def project_detail(request, slug):
	# return HttpResponse(slug)
	project = Project.objects.get(slug=slug)
	return render(request, 'portfolio/project_detail.html', {'project': project})

wannabeblog/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
	#return HttpResponse('homepage')
	return render(request, 'homepage.html')

def about(request):
	#return HttpResponse('about')
	return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'article:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="article-detail">
	<div class="article">
		<img src="{{ article.thumb.url }}" />
		<h2>{{article.title}}</h2>
		<p>{{article.body}}</p>
		<p>{{article.date}}</p>
	</div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}


{% block content %}
<h1>Hi and welcome</h1>
<p>My name is Yuliya and this is my blog about learning programming and other stuff. I've always wanted to know everything and while knowing absolutely everithing there is to know is not possible, it is absolutely possible to learn A LOT, to self improve and to try new things. This is kinda what I'm doing. And this blog is meant to document my path.</p>
<p>Learn a little more about this project <a>here</a> or a lot more by contacting me directly: kuroi.kasa1509@gmail.com</p>
<section class="info">
 <div class="column-1">
  <h4>WHO AM I</h4>
  <p>I'm a Front-End developer wannabe. I started as self taught programmer and than received Front-End developer Scholarship from Google. I work with HTML, CSS, JS and React, however, this blog is my experiment with Python and Django. I went the long way, but there is still so much to learn!</p>
</div>
<div class="column-2">
  <h4>BLOG'S PURPOSE</h4>
  <p>The purpose of this blog is to document my progress and motivate me to keep going. Sometimes it is hard to find that motivation. Sometimes the amount of information about one technology or the other seems SO overwhelming!  </p>
</div>
<div class="column-3">
  <h4>RECENT BOOKS AND INTERESTING ARTICLES</h4>
  <p></p>
</div>
</section>
<h1 class="article-list">Article List</h1>
<div class="articles">
 {% for article in articles %}
 <div class="article">
  <h2><a href="{% url 'article:detail' slug=article.slug %}">{{ article.title}}</a></h2>
  <p>{{ article.snippet }}</p>
  <p>{{ article.date }}</p>
  <p class="author">added by {{ article.author.username }}</p>
</div>
{% endfor %}
</div>
{% endblock %}

portfolio/templates/portfolio/project_detail.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" width="device-width", initial-scale="1">
	<title>Portfolio</title>
	<link rel='stylesheet' href='{% static "portfolio.css" %}'>
	<link rel='stylesheet' href='{% static "hover.css" %}'>
	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
</head>
<body>
	<div id="main">
		<header class="wrapper">
			<nav>
				<div class="logo">
					<h1><a href="{% url 'home' %}"><img src="{% static 'logo6.png' %}" class="home-logo" alt="home-logo" /></a></h1>
				</div>
				<ul class="nav-links">
					<li><a href="{% url 'about' %}">about</a></li>
					<li><a href="{% url 'article:list' %}">blog</a></li>
					<li><a href="{% url 'portfolio:list' %}">portfolio</a></li>
					<li><a href="{% static 'cv.pdf' %}" download="Yushkova_CV" class="hvr-bounce-to-right get-cv-btn">get CV</a></li>
				</ul>
				<div class="burger">
					<div class="line1"></div>
					<div class="line2"></div>
					<div class="line3"></div>
				</div>
			</nav>
		</header>
		{% block content %}

		<div class="project-detail">
			<div class="project-info">
				
				<div class="project-details">
					<h2>{{project.title}}</h2>
					<img src="{{ project.thumb.url }}" class="project-thumb" />
					<p>{{project.body}}</p>
					<div class="code-links">
						<p><a href="{{project.urlDemo}}" class="demo-link"><i class="fas fa-laptop"></i>Live <span>Demo</span></a></p>
						<p><a href="{{project.urlGit}}" class="github-link"><i class="fab fa-github"></i>Source <span>Code</span></a></p>
					</div>
					<div class="techno">
						<p>Technologies used</p>
						<ul class="techno-icons">
							<li><i class="fab fa-html5" title="HTML5"></i></li> 
							<li><i class="fab fa-css3-alt" title="CSS3"></i></li> 
							<li><i class="fab fa-react" title="React"></i></li> 
							<li><i class="fab fa-npm" title="npm"></i></li>
							<li><i class="fab fa-js-square" title="JavaScript"></i></li>
						</ul>
					</div>
					<p>{{project.date}}</p>
				</div>
			</div>
		</div>
<script src='{% static "app.js" %}'></script>  
		{% endblock %}

portfolio/templates/portfolio/project_list.html
	
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" width="device-width", initial-scale="1">
	<title>Portfolio</title>
	<link rel='stylesheet' href='{% static "portfolio.css" %}'>
	<link rel='stylesheet' href='{% static "hover.css" %}'>
	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,700" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
</head>
<body>
	<div id="main-project">
		<header class="wrapper">
			<nav>
				<div class="logo">
					<h1><a href="{% url 'home' %}"><img src="{% static 'logo7.png' %}" class="home-logo" alt="home-logo" /></a></h1>
				</div>
				<ul class="nav-links">
					<li><a href="{% url 'about' %}">about</a></li>
					<li><a href="{% url 'article:list' %}">blog</a></li>
					<li><a href="{% url 'portfolio:list' %}">portfolio</a></li>
					<li><a href="{% static 'cv.pdf' %}" download="Yushkova_CV" class="hvr-bounce-to-right get-cv-btn">get CV</a></li>
				</ul>
				<div class="burger">
					<div class="line1"></div>
					<div class="line2"></div>
					<div class="line3"></div>
				</div>
			</nav>
		</header>
		<div class="project-main">
			<h1 class="project-list">Project List</h1>
			
			<div class="list-whole">
				{% for project in project %}
				<div class="list-item">	
					<div class="img-container">
						<img class="thumb-img" src="{{ project.thumb.url }}" />
					</div>
					<div class="project-info-container">
						<h3 id="project-title"><a href="{{project.slug}}">{{ project.title }}</a></h3>
						<p>{{ project.body }}</p>
						<div class="code-links">
							<p><a href="{{project.urlDemo}}" class="demo-link"><i class="fas fa-laptop"></i>Live Demo</a></p>
							<p><a href="{{project.urlGit}}" class="github-link"><i class="fab fa-github"></i>Source Code</a></p>
						</div>
						<div class="techno">
							<p>Technologies used</p>
							<ul class="techno-icons">
								<li><i class="fab fa-html5" title="HTML5"></i></li> 
								<li><i class="fab fa-css3-alt" title="CSS3"></i></li> 
								<li><i class="fab fa-react" title="React"></i></li> 
								<li><i class="fab fa-npm" title="npm"></i></li>
								<li><i class="fab fa-js-square" title="JavaScript"></i></li>
							</ul>
						</div>
						<p class="project-date">{{ project.date }}</p>
					</div>
				</div>
				{% endfor %}
			</div>  
		</div>
		<script src='{% static "app.js" %}'></script>  
	</body>
	</html>

templates/about.html
	
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="Description" content="FRont-End developer Yushkova, responsive design, react, for hire">
	<title>Articles</title>
	<link rel='stylesheet' href='{% static "about.css" %}'>
	<link rel='stylesheet' href='{% static "hover.css" %}'>
	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
</head>
<body>
	<div id="about-main">
		<header class="wrapper-about-section">
			<nav class="nav-about-section">
				<div class="logo">
					<h1><a href="{% url 'home' %}"><img src="{% static 'logo7.png' %}" class="home-logo" alt="home-logo" /></a></h1>
				</div>
				<ul class="nav-links">
					<li><a href="{% url 'about' %}">about</a></li>
					<li><a href="{% url 'article:list' %}">blog</a></li>
					<li><a href="{% url 'portfolio:list' %}">portfolio</a></li>
					<li><a href="{% static 'cv.pdf' %}" download="Yushkova_CV" class="hvr-bounce-to-right get-cv-btn">get CV</a></li>
				</ul>
				<div class="burger">
					<div class="line1"></div>
					<div class="line2"></div>
					<div class="line3"></div>
				</div>
			</nav>
		</header>
		<section class="about-main">
			<div class="icons-all">
				<a href="https://www.linkedin.com/in/yuliya-yushkova/" target="_blank" rel="noopener"><img src="{% static 'linkedin_about.svg' %}" class="icon" alt="linkedin-icon"></a>
				<a href="mailto:kuroi.kasa1509@gmail.com" class="email-link" target="_blank" rel="noopener"><img src="{% static 'gmail_about.svg' %}" class="icon" alt="email-icon"></a>
				<a href=""><img src="{% static 'skype_about.svg' %}" class="icon" alt="skype-icon"></a>
				<a href="https://github.com/Yulya-Yu" target="_blank" rel="noopener"><img src="{% static 'git_about.svg' %}" class="icon" alt="github-icon"></a>
			</div>
			<div class="intro">
				<div class="intro-text">
					<h4>Hi, I'm Yuliya</h4>
					<h6><span>Front-End Developer</span> based in Tomsk, Russia.</h6>
					<p>I have a passion for web design and love to create clean and responsive layouts using the latest technologies available. If you have a project in mind, think you can use my help with something or just fancy saying hi, <span>get in touch.</span></p>
				</div>
			</div>
		</section>
		<section class="services">
			<h3>what can I do for you</h3>
			<div class="service-cards">
				<div class="card1">
					<h4>web-development</h4>
					<img src="{% static 'webdev.svg' %}" class="webdev service" />
					<p>I can develop a website using the lates, most efficient technologies available.</p>
				</div>
				<div class="card2">
					<h4>responsive web-design</h4>
					<img src="{% static 'respdesign.svg' %}" class="responsive design service" />
					<p>mobile-friendly website is no longer optional: it’s a necessity. It all starts with responsive web design.</p>
				</div>
				<div class="card3">
					<h4>maintenance & optimization</h4>
					<img src="{% static 'maint.svg' %}" class="maintenance & optimization service" />
					<p>to stay up-to-date websites should be maintained and optimized.</p>
				</div>
			</div>
		</section>
		<section class="tech-stack">
			<div class="tech-header">
				<h3>technologies I use</h3>
			</div>
			<div class="tech-info">
				<div class="tech-text">
					<p></p>
				</div>
				<div class="tech-icons">
					<div class="front-end-icons">
						<h4>Front-End</h4>
						<img src="{% static 'skills/logo-javascript.svg' %}" class="skill-icon" alt="javascript-icon" title="javascript"/>
						<img src="{% static 'skills/html-5.svg' %}" class="skill-icon" alt="html-icon" title="html"/>
						<img src="{% static 'skills/css.svg' %}" class="skill-icon" alt="css-icon" title="css"/>
					</div>
					<div class="libraries">
						<h4>Libraries</h4>
						<img src="{% static 'skills/react.svg' %}" class="skill-icon" alt="react-icon" title="react"/>
					</div>
					<div class="frameworks">
						<h4>Frameworks</h4>
						<img src="{% static 'skills/django.svg' %}" class="skill-icon" alt="django-icon" title="django"/>
					</div>
					<div class="other">
						<h4>Other</h4>
						<img src="{% static 'skills/github-icon.svg' %}" class="skill-icon" alt="github-icon" title="github"/>
						<img src="{% static 'skills/git-icon.svg' %}" class="skill-icon" alt="git-icon" title="git"/>
						<img src="{% static 'skills/ai.svg' %}" class="skill-icon" alt="ai-icon" title="Illustrator"/>
						<img src="{% static 'skills/npm.svg' %}" class="skill-icon" alt="npm-icon" title="npm"/>
					</div>
				</div>
			</div>
		</section>
	</div>
	<script src='{% static "app.js" %}'></script>  
</body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="Description" content="FRont-End developer Yushkova, responsive design, react, for hire">
	<title>Articles</title>
	<link rel='stylesheet' href='{% static "styles.css" %}'>
	<link href="https://fonts.googleapis.com/css?family=Ubuntu:400,500&amp;subset=cyrillic" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
</head>
<body>
	<section class="main-content">
		<header class="wrapper">
			<h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="home-logo" /></a></h1>
			<nav>
				<ul>
					<li><a href="{% url 'about' %}">About</a></li>
					<li><a href="{% url 'article:list' %}">Articles List</a></li>
					{% if user.is_authenticated %}

					<li>
						<form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
							{% csrf_token %}
							<button type="submit">Logout</button>
						</form>
					</li>
					<li><a href="{% url 'article:create' %}" class="highlight">New Article</a></li>

					{% else %}
					<li><a href="{% url 'accounts:login' %}">Login</a></li>
					<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
					{% endif %}
				</ul>
			</nav>
		</header>
		<div class="wrapper">
			{% block content %}
			{% endblock %}
		</div>
	</section>

</body>
</html>

templates/homepage.html
	
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="Description" content="Front-End developer Yushkova, responsive design, react, for hire">
	<title>Yushkova</title>
	<link rel='stylesheet' href='{% static "styles.css" %}'>
	<link rel='stylesheet' href='{% static "hover.css" %}'>
	
	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,700,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Rubik:400,900&display=swap&subset=cyrillic" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Megrim&display=swap" rel="stylesheet">
</head>
<body>
	<div id="main">
		<header class="wrapper">
			
			<nav>
				<div class="logo">
					<h1><a href="{% url 'home' %}"><img src="{% static 'logo7.png' %}" class="home-logo" alt="home-logo" /></a></h1>
				</div>
				<ul class="nav-links">
					<li><a href="{% url 'about' %}">about</a></li>
					<li><a href="{% url 'article:list' %}">blog</a></li>
					<li><a href="{% url 'portfolio:list' %}">portfolio</a></li>
					<li><a href="{% static 'cv.pdf' %}" download="Yushkova_CV" class=" get-cv-btn">get CV</a></li>
				</ul>
				<div class="burger">
					<div class="line1"></div>
					<div class="line2"></div>
					<div class="line3"></div>
				</div>
			</nav>
		</header>

		<div class="main-header">
			<div class="icons-all">
				<a href="https://www.linkedin.com/in/yuliya-yushkova/" target="_blank" rel="noopener"><img src="{% static 'linkedin_about.svg' %}" class="icon" alt="linkedin-icon"></a>
				<a href="mailto:kuroi.kasa1509@gmail.com" class="email-link" target="_blank" rel="noopener"><img src="{% static 'gmail_about.svg' %}" class="icon" alt="email-icon"></a>
				<a href=""><img src="{% static 'skype_about.svg' %}" class="icon" alt="skype-icon"></a>
				<a href="https://github.com/Yulya-Yu" target="_blank" rel="noopener"><img src="{% static 'git_about.svg' %}" class="icon" alt="github-icon"></a>
			</div>
			<div class="intro-home">
				<h1>Yuliya <span>Yushkova</span></h1>
				<p class="main-text">front-end developer.</p>
				<button class="learn-more-btn hvr-sweep-to-right"><a href="{% url 'about' %}">Learn more</a></button>
			</div>

		<!--	<div class="intro-message">
				<p>Hi, I'm Yuliya! An aspiring Front-End Developer based in Tomsk, Russia. I have a passion for web design and love to create clean and responsive layouts using the latest technologies available. If you have a project in mind, think you can use my help with something or just fancy saying hi, get in touch.</p>
				
			</div> -->

		</div>
		
	</div>
<!--	<section class="introduction">
		<h3>Hi, I'm <span>Yuliya</span></h3>
		<hr/>
		<p>Front-End Developer based in Tomsk, Russia. I have a passion for web design and love to create clean and responsive layouts using the latest technologies available. If you have a project in mind, think you can use my help with something or just fancy saying hi, get in touch.</p>
	</section>
	<section class="services">
		<h3>What can I do for you</h3>
		<hr/>
		<p>Front-End Developer based in Tomsk, Russia. I have a passion for web design and love to create clean and responsive layouts using the latest technologies available. If you have a project in mind, think you can use my help with something or just fancy saying hi, get in touch.</p>
	</section>
	<section class="tech-stack">
		<div class="tech-header">
			<h1>Skills</h1>
		</div>
		<div class="tech-icons">
			<img src="{% static 'skills/logo-javascript.svg' %}" class="skill-icon" alt="javascript-icon" title="javascript"/>
			<img src="{% static 'skills/react.svg' %}" class="skill-icon" alt="react-icon" title="react"/>
			<img src="{% static 'skills/nodejs-1.svg' %}" class="skill-icon" alt="node-icon" title="node.js"/>
			<img src="{% static 'skills/npm.svg' %}" class="skill-icon" alt="npm-icon" title="npm"/>
			<img src="{% static 'skills/django.svg' %}" class="skill-icon" alt="django-icon" title="django"/>
			<img src="{% static 'skills/html-5.svg' %}" class="skill-icon" alt="html-icon" title="html"/>
			<img src="{% static 'skills/css.svg' %}" class="skill-icon" alt="css-icon" title="css"/>
			<img src="{% static 'skills/github-icon.svg' %}" class="skill-icon" alt="github-icon" title="github"/>
			<img src="{% static 'skills/git-icon.svg' %}" class="skill-icon" alt="git-icon" title="git"/>
			<img src="{% static 'skills/ai.svg' %}" class="skill-icon" alt="ai-icon" title="Illustrator"/>
		</div>
	</section> -->
	<script src='{% static "app.js" %}'></script>  
</body>
</html>

templates/portfolio.html
	
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="Description" content="Front-End developer Yushkova, responsive design, react, for hire">
	<title>Portfolio</title>
	<link rel='stylesheet' href='{% static "styles.css" %}'>
	<link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway:300,400,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
</head>
<body>
	<div class="main">
		<header class="wrapper">
			<h1><a href="{% url 'home' %}"><img src="{% static 'logo1.png' %}" /></a></h1>
			<nav>
				<ul>
					<li><a href="{% url 'about' %}">about</a></li>
					<li><a href="{% url 'article:list' %}">blog</a></li>
					<li><a href="{% static 'cv.pdf' %}" download="Yushkova_CV" class="highlight">get CV</a></li>

				</ul>
			</nav>
		</header>

	</body>
	</html>